#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DnDAppAndroid.Resource", IsApplication=true)]

namespace DnDAppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackButtonImg = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int aignmentSelector = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int alignmentLayout = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int back = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int characterName = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int classLayout = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int classSelector = 2131099661;
			
			// aapt resource value: 0x7f06001a
			public const int copperAmount = 2131099674;
			
			// aapt resource value: 0x7f06001f
			public const int copperAmount_incr = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int copper_modif = 2131099680;
			
			// aapt resource value: 0x7f060027
			public const int createChar = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int experience = 2131099686;
			
			// aapt resource value: 0x7f06000e
			public const int experienceAmount = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int experienceAmount_incr = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int experience_modif = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int goldAmount = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int goldAmount_incr = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int gold_modif = 2131099676;
			
			// aapt resource value: 0x7f060014
			public const int increase_experience = 2131099668;
			
			// aapt resource value: 0x7f060021
			public const int increase_money = 2131099681;
			
			// aapt resource value: 0x7f060025
			public const int inventory = 2131099685;
			
			// aapt resource value: 0x7f06000f
			public const int levelAmount = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060028
			public const int loadChar = 2131099688;
			
			// aapt resource value: 0x7f060024
			public const int manage_gold = 2131099684;
			
			// aapt resource value: 0x7f060010
			public const int proficiencyAmount = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int raceLayout = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int raceSelector = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int reset_experience = 2131099670;
			
			// aapt resource value: 0x7f060023
			public const int reset_money = 2131099683;
			
			// aapt resource value: 0x7f060017
			public const int scrollView1 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int silverAmount = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int silverAmount_incr = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int silver_modif = 2131099678;
			
			// aapt resource value: 0x7f060013
			public const int splitAmount_incr = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int split_experience = 2131099669;
			
			// aapt resource value: 0x7f060022
			public const int split_money = 2131099682;
			
			// aapt resource value: 0x7f060008
			public const int subRaceLayout = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int subRaceSelector = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int textView3 = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int createChar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int experience = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int goldPouch = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int inventory = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int loadChar = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int alignment_prompt = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int class_prompt = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int race_prompt = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int subRace_prompt = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
